---@type vim.lsp.Config
return {
	cmd = { "tailwindcss-language-server", "--stdio" },
	filetypes = {
		"astro",
		"blade",
		"clojure",
		"htmldjango",
		"eelixir",
		"elixir",
		"eruby",
		"haml",
		"handlebars",
		"html",
		"htmlangular",
		"heex",
		"liquid",
		"markdown",
		"mustache",
		"php",
		"razor",
		"twig",
		"css",
		"less",
		"sass",
		"scss",
		"stylus",
		"javascript",
		"javascriptreact",
		"rescript",
		"typescript",
		"typescriptreact",
		"vue",
		"svelte",
		"templ",
	},
	root_markers = { "Dockerfile" },
	settings = {
		tailwindCSS = {
			classAttributes = { "class", "className", "class:list", "classList", "ngClass" },
			includeLanguages = {
				eelixir = "html-eex",
				eruby = "erb",
				htmlangular = "html",
				templ = "html",
			},
			lint = {
				cssConflict = "warning",
				invalidApply = "error",
				invalidConfigPath = "error",
				invalidScreen = "error",
				invalidTailwindDirective = "error",
				invalidVariant = "error",
				recommendedVariantOrder = "warning",
			},
			validate = true,
		},
	},
	workspace_required = true,
}
